### ISSUE TITLE
Display Diff in Browser

### ISSUE THREAD

**Issue by infogulch** [vshih/CloudDiff#1]
You could use the [jsdiff lib](https://github.com/cemerick/jsdifflib) to do the diff right there, but then allow users to open a custom diff tool on their computer if they want.

**Comment by vshih** [comment]
Great reference, thanks.  I was already considering doing the diff in javascript but didn't know of jsdifflib.

**Comment by vshih** [comment]
Functionality restored since 1.0.2.14.
