### ISSUE TITLE
Repository description points to invalid link

### ISSUE THREAD

**Issue by nyanpasu64** [vshih/CloudDiff#3]
>Diff tool for Dropbox, pCloud https://chrome.google.com/webstore/de…

The description points to https://chrome.google.com/webstore/detail/aefdkgcdokdiaoppobphjogcilaaakka (broken)

The readme points to https://chrome.google.com/webstore/detail/clouddiff/hlmlielnekakcdfpkbgcpnphenleogfp (this works)

**Comment by vshih** [comment]
Updated; thanks!
